pluginManagement {
    includeBuild('build-logic')
}

rootProject.name = 'bank-application'

include('loan-svc')
include('loan-core')
include('cust-core')
include('arrangement-core')
include('deposit-core')
include('bank-common')
include('bank-common-core')

include('product-svc')
include('product-api')
include('product-core')
